# Generated by Django 5.2 on 2025-05-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('animal', models.CharField(max_length=200)),
                ('behavior', models.CharField(choices=[('Feeding', 'Feeding'), ('Resting', 'Resting'), ('Active', 'Active'), ('Other', 'Other')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
